---
- name: Check if disk encryption is enabled in iso
  ansible.builtin.shell:
    cmd: 'lsblk | grep crypt | wc -l'
  register: potos_firstboot_is_crypt
  changed_when: false

- name: Change disk encryption password
  ansible.builtin.shell:
    executable: '/bin/bash'
    cmd: |
      while ([ ${POTOS_NEW_LUKS_PW} != ${POTOS_NEW_LUKS_PW2} ] || [ -z ${POTOS_NEW_LUKS_PW2} ] || [ -z ${POTOS_OLD_LUKS_PW_TEST} ]); do
        USERINPUT="$(yad --fullscreen --title '{{ potos_firstboot_client_name }} Setup' \
          --borders 20 --align center \
          --button gtk-ok \
          --button "Change keyboard layout":"/setup/change-keyboard-layout.sh" \
          --image-on-top --image=/setup/logo.png \
          --text \
      "Your disk encryption password needs to be changed now, because the default password is unsecure.

      IMPORTANT: Do not forget your disk encryption boot password! Please note your disk encryption boot password on a very safe plase.

      Please enter your new disk encryption password below
      " \
          --form \
          --field 'Current disk encryption password:H' \
          --field 'New disk encryption password:H' \
          --field 'Confirm new disk encryption password:H'
        )"

        #Save UserInput
        POTOS_OLD_LUKS_PW="$(echo ${USERINPUT} | cut -d '|' -f 1)"
        POTOS_NEW_LUKS_PW="$(echo ${USERINPUT} | cut -d '|' -f 2)"
        POTOS_NEW_LUKS_PW2="$(echo ${USERINPUT} | cut -d '|' -f 3)"

        #Test POTOS_OLD_LUKS_PW if the given Password is correct.
          eval "$(awk '/crypt/ {print $2}' /etc/crypttab)" && LUKS_DEVICE="$(realpath "/dev/disk/by-uuid/${UUID}")"
          printf "${POTOS_OLD_LUKS_PW}" | sudo cryptsetup luksOpen --test-passphrase $LUKS_DEVICE
        if [ $? -eq 0 ]; then
          POTOS_OLD_LUKS_PW_TEST="correct"
        fi

        if [ -z ${POTOS_OLD_LUKS_PW_TEST} ]; then
          yad --title "{{ potos_firstboot_client_name }} Setup" \
            --borders 20 --align center --button gtk-ok --image-on-top \
            --image=/setup/logo.png \
            --text 'The given old disk encryption password was incorrect. Please try again.'
        fi

        if [ -z ${POTOS_NEW_LUKS_PW} ] || [ -z ${POTOS_NEW_LUKS_PW2} ]; then
          yad --title "{{ potos_firstboot_client_name }} Setup" \
            --borders 20 --align center --button gtk-ok --image-on-top \
            --image=/setup/logo.png \
            --text 'Please choose and enter your new credentials.'
        fi
        if [  ${POTOS_NEW_LUKS_PW} != ${POTOS_NEW_LUKS_PW2} ]; then
          yad --title "{{ potos_firstboot_client_name }} Setup" \
            --borders 20 --align center --button gtk-ok --image-on-top \
            --image=/setup/logo.png \
            --text 'Your password was not identical. Please try again.'
        fi
      done

      #Change disk encryption password now
      eval "$(awk '/crypt/ {print $2}' /etc/crypttab)" && LUKS_DEVICE="$(realpath "/dev/disk/by-uuid/${UUID}")"
      printf '%s\n' "${POTOS_OLD_LUKS_PW}" "${POTOS_NEW_LUKS_PW}" | cryptsetup luksChangeKey "${LUKS_DEVICE}" -q
      if [[ $? -ne 0 ]]; then
        echo "# Failed to change primary disk encryption key."
        exit 1
      fi
  when:
    - potos_firstboot_ask_change_disk_enc_pw
    - potos_firstboot_is_crypt.stdout != '0'
  tags:
    - 'molecule-notest'
