---

- name: Prepare
  hosts: all
  gather_facts: yes

  tasks:
  # Update the apt cache as it's potentialy outdated in the container
  - name: update apt
    ansible.builtin.shell:  # noqa: command-instead-of-module
      cmd: 'apt-get update && apt-get upgrade -y'
    when: ansible_distribution == 'Ubuntu'
  - name: install gnome
    ansible.builtin.apt:
      name: '{{ item }}'
      state: present
    loop:
      - 'gnome-session'
      - 'gdm3'

  - name: create setup directory
    ansible.builtin.file:
      dest: /setup
      state: directory
      mode: 0755

  - name: download env
    ansible.builtin.get_url:
      url: https://raw.githubusercontent.com/projectpotos/potos-iso-builder/main/.env
      dest: /setup/.env
      mode: 0644
